import { FC } from "react";
import { Container, Box } from "@chakra-ui/layout";
import Head from "next/head";

import { Navbar } from "components";

export const PageLayout: FC = ({ children }) => {
  return (
    <div>
      <Head>
        <title>SpaceX Launches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Container maxW="container.lg" py="4">
          {children}
        </Container>
      </main>

      <footer></footer>
    </div>
  );
};
