import { FC } from "react";
import { Container, Grid } from "@chakra-ui/layout";
import Head from "next/head";

import { Navbar, Footer } from "components";

export const PageLayout: FC = ({ children }) => {
  return (
    <div>
      <Head>
        <title>SpaceX Launches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid h="100vh" gridTemplateRows="auto 1fr auto">
        <Navbar />
        <main>
          <Container maxW="container.lg" py="4">
            {children}
          </Container>
        </main>

        <Footer />
      </Grid>
    </div>
  );
};
